///|/ Copyright (c) Prusa Research 2025
///|/
///|/ PrusaSlicer is released under the terms of the AGPLv3 or higher
///|/
#include "CloudSync.hpp"
#include "libslic3r/AppConfig.hpp"

#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/xml_parser.hpp>
#include <boost/algorithm/string.hpp>
#include <boost/algorithm/hex.hpp>
#include <boost/nowide/fstream.hpp>
#include <boost/filesystem.hpp>
#include <boost/log/trivial.hpp>
#include <boost/format.hpp>
#include <boost/uuid/detail/md5.hpp>

#include <wx/string.h>

#include <sstream>
#include <ctime>
#include <iomanip>

namespace fs = boost::filesystem;

namespace Slic3r {

// Calculate MD5 hash from data, skipping PrusaSlicer timestamp header for deterministic comparison
std::string calculate_config_bundle_hash(const char* data, size_t size)
{
    using boost::uuids::detail::md5;

    // Check if data starts with timestamp header and skip it
    const char* data_start = data;
    size_t data_size = size;

    // Look for "# generated by PrusaSlicer" or "# generated by GCodeViewer" at the start
    if (size > 26 && (std::strncmp(data, "# generated by PrusaSlicer", 26) == 0 ||
                      std::strncmp(data, "# generated by GCodeViewer", 26) == 0)) {
        // Skip first line (find first newline)
        const char* newline = static_cast<const char*>(std::memchr(data, '\n', size));
        if (newline) {
            data_start = newline + 1;
            data_size = size - (data_start - data);
        }
    }

    md5 md5_hash;
    md5::digest_type md5_digest{};
    md5_hash.process_bytes(data_start, data_size);
    md5_hash.get_digest(md5_digest);

    std::string md5_digest_str;
    boost::algorithm::hex(md5_digest, md5_digest + std::size(md5_digest), std::back_inserter(md5_digest_str));

    return md5_digest_str;
}

// Parse HTTP date format (RFC 2616/RFC 1123)
// Example: "Mon, 15 Oct 2025 23:03:45 GMT"
static time_t parse_http_date(const std::string &date_str) {
    if (date_str.empty()) {
        return 0;
    }

    std::tm tm = {};
    std::istringstream ss(date_str);

    // Try RFC 1123 format: "Day, DD Mon YYYY HH:MM:SS GMT"
    ss >> std::get_time(&tm, "%a, %d %b %Y %H:%M:%S");

    if (ss.fail()) {
        // Try alternate format without day name: "DD Mon YYYY HH:MM:SS GMT"
        ss.clear();
        ss.str(date_str);
        ss >> std::get_time(&tm, "%d %b %Y %H:%M:%S");
    }

    if (ss.fail()) {
        return 0; // Failed to parse
    }

    // Convert to time_t (assuming GMT/UTC)
    #ifdef _WIN32
        return _mkgmtime(&tm);
    #else
        return timegm(&tm);
    #endif
}

// CloudSyncWebDAV implementation

CloudSyncWebDAV::CloudSyncWebDAV(const std::string &url, const std::string &username, const std::string &password)
{
    m_url = url;
    m_username = username;
    m_password = password;

    // Ensure URL doesn't end with slash
    if (!m_url.empty() && m_url.back() == '/') {
        m_url.pop_back();
    }
}

std::string CloudSyncWebDAV::make_url(const std::string &path) const
{
    std::string url = m_url;
    if (!path.empty()) {
        if (path.front() != '/') {
            url += "/";
        }
        url += path;
    }
    return url;
}

// Helper to extract path component from URL (removes protocol and domain)
static std::string extract_url_path_component(const std::string &url)
{
    size_t path_start = url.find("://");
    if (path_start != std::string::npos) {
        path_start = url.find('/', path_start + 3);
        if (path_start != std::string::npos) {
            return url.substr(path_start);
        }
    }
    return url;
}

Http CloudSyncWebDAV::create_http_request(const std::string &url) const
{
    auto http = Http::get(url);
    if (!m_username.empty()) {
        http.auth_basic(m_username, m_password);
    }
    return http;
}

bool CloudSyncWebDAV::is_http_success(unsigned status)
{
    return status >= 200 && status < 300;
}

Http::ErrorFn CloudSyncWebDAV::create_error_handler(bool &success, ErrorFn error_fn) const
{
    return [&success, error_fn](std::string body, std::string error, unsigned status) {
        if (error_fn) {
            wxString err_msg = wxString::FromUTF8((error.empty() ? body : error).c_str());
            error_fn(err_msg);
        }
        success = false;
    };
}

std::string CloudSyncWebDAV::extract_filename(const std::string &path)
{
    size_t last_slash = path.find_last_of('/');
    if (last_slash != std::string::npos) {
        return path.substr(last_slash + 1);
    }
    return path;
}

bool CloudSyncWebDAV::upload_file(const boost::filesystem::path &local_path,
                                  const std::string &remote_path,
                                  ProgressFn progress_fn,
                                  ErrorFn error_fn) const
{
    bool success = false;
    std::string url = make_url(remote_path);

    BOOST_LOG_TRIVIAL(debug) << boost::format("CloudSync: Uploading %1% -> %2%")
        % local_path.string() % remote_path;

    auto http = Http::put(url);
    if (!m_username.empty()) {
        http.auth_basic(m_username, m_password);
    }

    http.set_put_body(local_path)
        .on_error(create_error_handler(success, error_fn))
        .on_complete([&](std::string body, unsigned status) {
            success = is_http_success(status);
        });

    if (progress_fn) {
        http.on_progress([&](Http::Progress progress, bool &cancel) {
            progress_fn(progress, cancel);
        });
    }

    http.perform_sync();
    return success;
}

bool CloudSyncWebDAV::download_file(const std::string &remote_path,
                                   const boost::filesystem::path &local_path,
                                   ProgressFn progress_fn,
                                   ErrorFn error_fn) const
{
    BOOST_LOG_TRIVIAL(debug) << boost::format("CloudSync: Downloading %1% -> %2%")
        % remote_path % local_path.string();
    bool success = false;
    std::string url = make_url(remote_path);
    std::string content;

    auto http = create_http_request(url);

    http.on_error(create_error_handler(success, error_fn))
        .on_complete([&](std::string body, unsigned status) {
            if (is_http_success(status)) {
                content = body;
                success = true;
            }
        });

    if (progress_fn) {
        http.on_progress([&](Http::Progress progress, bool &cancel) {
            progress_fn(progress, cancel);
        });
    }

    http.perform_sync();

    if (success && !content.empty()) {
        // Write content to local file
        boost::nowide::ofstream file(local_path.string(), std::ios::binary);
        if (file.is_open()) {
            file.write(content.c_str(), content.size());
            file.close();
        } else {
            success = false;
            if (error_fn) {
                error_fn(wxString::FromUTF8("Failed to write local file"));
            }
        }
    }

    return success;
}

bool CloudSyncWebDAV::list_files(const std::string &remote_path,
                                std::vector<CloudFile> &files,
                                ErrorFn error_fn) const
{
    bool success = false;
    std::string url = make_url(remote_path);
    std::string response_body;

    // WebDAV PROPFIND request
    std::string propfind_body =
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
        "<D:propfind xmlns:D=\"DAV:\">"
        "  <D:prop>"
        "    <D:displayname/>"
        "    <D:getcontentlength/>"
        "    <D:getlastmodified/>"
        "    <D:resourcetype/>"
        "  </D:prop>"
        "</D:propfind>";

    auto http = create_http_request(url);

    http.custom_request("PROPFIND")
        .header("Depth", "1")
        .header("Content-Type", "application/xml; charset=utf-8")
        .set_post_body(propfind_body)
        .on_error(create_error_handler(success, error_fn))
        .on_complete([&](std::string body, unsigned status) {
            if (is_http_success(status)) {
                response_body = body;
                success = true;
            }
        });

    http.perform_sync();

    if (success) {
        success = parse_propfind_response(response_body, files);
        if (!success && error_fn) {
            error_fn(wxString::FromUTF8("Failed to parse WebDAV response"));
        }
    }

    return success;
}

bool CloudSyncWebDAV::parse_propfind_response(const std::string &xml_response,
                                             std::vector<CloudFile> &files) const
{
    try {
        std::istringstream is(xml_response);
        boost::property_tree::ptree pt;
        boost::property_tree::read_xml(is, pt);

        // Parse WebDAV multistatus response
        for (const auto &response : pt.get_child("D:multistatus")) {
            if (response.first != "D:response") continue;

            CloudFile file;

            auto href = response.second.get_optional<std::string>("D:href");
            if (!href) continue;

            // Strip the base URL from href if present
            std::string href_str = extract_url_path_component(*href);
            std::string url_path = extract_url_path_component(m_url);

            // Remove url_path from beginning of href_str if present
            if (!url_path.empty() && href_str.find(url_path) == 0) {
                href_str = href_str.substr(url_path.length());
            }

            file.path = href_str;
            file.name = extract_filename(file.path);

            auto propstat = response.second.get_child_optional("D:propstat");
            if (!propstat) continue;

            auto prop = propstat->get_child_optional("D:prop");
            if (!prop) continue;

            // Get file size
            auto size = prop->get_optional<size_t>("D:getcontentlength");
            if (size) {
                file.size = *size;
            }

            // Check if it's a directory
            auto resourcetype = prop->get_child_optional("D:resourcetype");
            file.is_directory = (resourcetype && resourcetype->get_child_optional("D:collection"));

            // Get modification time
            auto lastmod = prop->get_optional<std::string>("D:getlastmodified");
            if (lastmod) {
                file.modified_time = parse_http_date(*lastmod);
            }

            // Skip hash calculation for directories
            if (!file.is_directory) {
                // Download file content and compute hash
                std::string url = make_url(file.path);
                std::string content;
                bool hash_success = false;

                auto http = create_http_request(url);
                http.on_error([](std::string body, std::string error, unsigned status) {
                    // Silently skip hash calculation on error
                })
                .on_complete([&](std::string body, unsigned status) {
                    if (is_http_success(status)) {
                        content = body;
                        hash_success = true;
                    }
                });
                http.perform_sync();

                if (hash_success && !content.empty()) {
                    file.hash = calculate_config_bundle_hash(content.c_str(), content.size());
                }
            }

            files.push_back(file);
        }

        return true;
    } catch (const std::exception &e) {
        return false;
    }
}

bool CloudSyncWebDAV::delete_file(const std::string &remote_path,
                                 ErrorFn error_fn) const
{
    bool success = false;
    std::string url = make_url(remote_path);

    auto http = create_http_request(url);

    http.custom_request("DELETE")
        .on_error([&](std::string body, std::string error, unsigned status) {
            if (error_fn) {
                wxString err_msg = wxString::FromUTF8((error.empty() ? body : error).c_str());
                error_fn(err_msg);
            }
            success = false;
        })
        .on_complete([&](std::string body, unsigned status) {
            success = is_http_success(status);
        });

    http.perform_sync();

    return success;
}

bool CloudSyncWebDAV::create_directory(const std::string &remote_path,
                                      ErrorFn error_fn) const
{
    bool success = false;
    std::string url = make_url(remote_path);

    auto http = create_http_request(url);

    http.custom_request("MKCOL")
        .on_error([&](std::string body, std::string error, unsigned status) {
            // 405 (Method Not Allowed) may be returned when directory already exists
            if (status != 405) {
                BOOST_LOG_TRIVIAL(debug) << boost::format("CloudSync: MKCOL failed - HTTP %1%: %2%")
                    % status % error;
                if (error_fn) {
                    wxString err_msg = wxString::FromUTF8((error.empty() ? body : error).c_str());
                    error_fn(err_msg);
                }
                success = false;
            } else {
                // Directory already exists - treat as success
                success = true;
            }
        })
        .on_complete([&](std::string body, unsigned status) {
            success = is_http_success(status) || status == 405; // 405 if already exists
        });

    http.perform_sync();

    return success;
}

} // namespace Slic3r
